blog/urls.py
from django.contrib import admin
from django.urls import path
from .views import BlogDetailView, BlogListView, BlogCreateView, BlogUpdateView, BlogDeleteView

app_name="blog"
urlpatterns = [
    path('', BlogListView.as_view(), name="home"),
    path('create/', BlogCreateView.as_view(), name="create"),
    path('<int:pk>/', BlogDetailView.as_view(), name="detail"),
    path('<int:pk>/update/', BlogUpdateView.as_view(), name="update"),
    path('<int:pk>/delete/', BlogDeleteView.as_view(), name="delete"),
]

core/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from .views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',HomeView.as_view(), name="home"),
    path('blog/',include('blog.urls', namespace='blog'))
]

blog/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField(max_length=250)
    content = models.TextField()

    def __str__(self):
        return self.title

blog/forms.py
from django import forms
from .models import Post

class PostCreateForm(forms.ModelForm):
    class Meta:
        model=Post
        fields=('title','content')

blog/views.py
from django import forms
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views.generic import View, UpdateView, DeleteView
from blog.models import Post
from .forms import PostCreateForm

class BlogListView(View):
    def get(self, request, *args, **kwargs):
        posts = Post.objects.all()
        context={
            'posts':posts
        }
        return render(request, 'blog_list.html', context)

class BlogCreateView(View):
    def get(self, request, *args, **kwargs):
        form=PostCreateForm()
        context={
            'form':form
        }
        return render(request, 'blog_create.html', context)

    def post(self, request, *args, **kwargs):
        if request.method=="POST": 
            form = PostCreateForm(request.POST)
            if form.is_valid():
                title = form.cleaned_data.get('title')
                content = form.cleaned_data.get('content')
                p, created = Post.objects.get_or_create(title=title, content=content)
                p.save()
                return redirect('blog:home')
        context={
            
        }
        return render(request, 'blog_create.html', context)


class BlogDetailView(View):
        def get(self, request, pk, *args, **kwargs):
            post= get_object_or_404(Post, pk=pk)
            context={
                'post':post
            }
            return render(request, 'blog_detail.html', context)


class BlogUpdateView(UpdateView):
    model=Post
    fields=['title','content']
    template_name='blog_update.html'

    def get_success_url(self):
        pk = self.kwargs['pk']
        return reverse_lazy('blog:detail', kwargs={'pk':pk})

class BlogDeleteView(DeleteView):
    model=Post
    template_name='blog_delete.html'
    success_url=reverse_lazy('blog:home')

core/views.py
from django.views.generic import View
from django.shortcuts import render


class HomeView (View):
    def get(self, request, *args, **kwargs):
        context={

        }
        return render(request, 'index.html', context)

templates/base.html
{% load tailwind_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% tailwind_css %}
    <title>Document</title>
</head>
<body>
    {% block content %}{% endblock content %}
</body>
</html>

templates/blog_create.html
<form method="POST">
{% csrf_token %}
title{{form.title}}
<br>
content{{form.content}}
<button type="submit">Submit</button>
</form>

templates/blog_delete.html
Are you sure?
<form method="POST">
{% csrf_token %}
{{form}}
<button type="submit">Delete</button>
</form>

templates/blog_detail.html
{{post.title}}
<br>
{{post.content}}

templates/blog_list.html
{% extends 'base.html' %}

{% block content %}
blog list
<br>
{%for post in posts%}
<a href="{% url 'blog:detail' post.id %}">{{post.title}}</a>
<a href="{% url 'blog:update' post.id %}">Update</a>
<a href="{% url 'blog:delete' post.id %}">Delete</a>
{% endfor %}
<br>
<a href="{% url 'blog:create' %}">Create</a>

{% endblock content %}

templates/blog_update.html
<form method="POST">
{% csrf_token %}
title{{form.title}}
<br>
content{{form.content}}
<button type="submit">Update</button>
</form>

templates/index.html
{% extends 'base.html' %}

{% block content %}hola, visita mi <a class="text-blue-500" href="{% url 'blog:home' %}"> blog aqui{% endblock content %}

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>